import locale

tab_files_name = "tab_files_name"
tab_files_name = "tab_files_name"
tab_options_name = "tab_options_name"
tab_options_name = "tab_options_name"
tab_processing_name = "tab_processing_name"
tab_processing_name = "tab_processing_name"
tab_debug_name = "tab_debug_name"
tab_debug_name = "tab_debug_name"
tab_help_name = "tab_help_name"
tab_help_name = "tab_help_name"

frame_files_name = "frame_files_name"
frame_output_name = "frame_output_name"
frame_options_name = "frame_options_name"
frame_processing_name = "frame_processing_name"
frame_progress_name = "frame_progress_name"
frame_debug_name = "frame_debug_name"
frame_help_name = "frame_help_name"
frame_threads_name = "frame_threads_name"
frame_command_name = "frame_command_name"

button_close_name = "button_close_name"
button_files_name = "button_files_name"
button_remove_name = "button_remove_name"
button_allremove_name = "button_allremove_name"
button_output_name = "button_output_name"
button_convert_name = "button_convert_name"
button_cancel_name = "button_cancel_name"
button_emptylogs_name = "button_emptylogs_name"

label_h264_name = "label_h264_name"
label_help_files_name1 = "label_help_files_name1"
label_help_files_name2 = "label_help_files_name2"
label_forindv_name = "label_forindv_name"
label_foroutdv_name= "label_foroutdv_name"
label_otheropt_name = "label_otheropt_name"
label_opt_recommanded = "label_opt_recommanded"
label_inwait = "label_inwait"

error_label = "error_label"
error_ffmpeg = "error_ffmpeg"
error_nofiles = "error_nofiles"
error_nodest = "error_nodest"
error_read_time = "error_read_time"
quest_recommanded = "quest_recommanded"
title_selection_file = "title_selection_file"
title_video_files = "title_video_files"
title_select_output = "title_select_output"
confirmation_remove_label = "confirmation_remove_label"
conversion_inprogress = "conversion_inprogress"
end_batch = "end_batch"
end_batch_notice = "end_batch_notice"
cuda_unknown = "cuda_unknown"

lang, enc = locale.getdefaultlocale()

dict={}
dict['fr_FR'] = {}
dict['en_US'] = {}

dict['fr_FR'][error_label] = "Erreur"
dict['en_US'][error_label] = "Error"
dict['fr_FR'][error_ffmpeg] = "FFmpeg ou ffprobe n'est pas installé ou n'est pas dans le PATH."
dict['en_US'][error_ffmpeg] = "FFmpeg or ffprobe is not installed or not in the PATH."
dict['fr_FR'][error_nofiles] = "Aucun fichier vidéo sélectionné."
dict['en_US'][error_nofiles] = "No video files selected."
dict['fr_FR'][error_nodest] = "Aucun répertoire de destination sélectionné."
dict['en_US'][error_nodest] = "No output directory selected."
dict['fr_FR'][quest_recommanded] = "Conversion recommandée"
dict['en_US'][quest_recommanded] = "Recommended Conversion"
dict['fr_FR'][title_selection_file] = "Sélectionner des fichiers vidéo"
dict['en_US'][title_selection_file] = "Select Video Files"
dict['fr_FR'][title_video_files] = "Fichiers vidéo"
dict['en_US'][title_video_files] = "Video Files"
dict['fr_FR'][title_select_output] = "Sélectionner le répertoire de sortie"
dict['en_US'][title_select_output] = "Select Output Directory"
dict['fr_FR'][confirmation_remove_label] = "Effacer toute la liste ?"
dict['en_US'][confirmation_remove_label] = "Clear the entire list ?"
dict['fr_FR'][conversion_inprogress] = "Conversion en cours"
dict['en_US'][conversion_inprogress] = "Conversion in progress"
dict["fr_FR"][error_read_time] = "Impossible de lire la durée de la vidéo."
dict["en_US"][error_read_time] = "Unable to read video duration."
dict['fr_FR'][end_batch] = "Fin de la conversion"
dict['en_US'][end_batch] = "End of conversion"
dict['fr_FR'][end_batch_notice] = "Tous les fichiers ont été traités."
dict['en_US'][end_batch_notice] = "All files have been processed."
dict['fr_FR'][cuda_unknown] = "Mode inconnu ou non disponible sans CUDA."
dict['en_US'][cuda_unknown] = "Unknown mode or unavailable without CUDA."

dict['fr_FR'][tab_files_name] = "Fichiers"
dict['en_US'][tab_files_name] = "Files"
dict['fr_FR'][tab_options_name] = "Options"
dict['en_US'][tab_options_name] = "Options"
dict['fr_FR'][tab_processing_name] = "Traitement"
dict['en_US'][tab_processing_name] = "Processing"
dict['fr_FR'][tab_debug_name] = "Débogage"
dict['en_US'][tab_debug_name] = "Debugging"
dict['fr_FR'][tab_help_name] = "Aide"
dict['en_US'][tab_help_name] = "Help"
dict['fr_FR'][button_close_name] = "Fermer"
dict['en_US'][button_close_name] = "Close"
dict['fr_FR'][button_files_name] = "Ajouter des fichiers"
dict['en_US'][button_files_name] = "Add Files"
dict['fr_FR'][button_remove_name] = "Supprimer la sélection"
dict['en_US'][button_remove_name] = "Remove Selection"
dict['fr_FR'][button_allremove_name] = "Tout supprimer"
dict['en_US'][button_allremove_name] = "Remove All"
dict['fr_FR'][button_output_name] = "Répertoire de sortie"
dict['en_US'][button_output_name] = "Output Directory"
dict['fr_FR'][button_convert_name] = "Convertir"
dict['en_US'][button_convert_name] = "Convert"
dict['fr_FR'][button_cancel_name] = "Annuler"
dict['en_US'][button_cancel_name] = "Cancel"
dict['fr_FR'][button_emptylogs_name] = "Vider les logs"
dict['en_US'][button_emptylogs_name] = "Empty Logs"

dict["fr_FR"][frame_files_name] = "Sélection des fichiers"
dict["en_US"][frame_files_name] = "File Selection"
dict["fr_FR"][frame_output_name] = "Répertoire de sortie"
dict["en_US"][frame_output_name] = "Output Directory"
dict["fr_FR"][frame_options_name] = "Options de conversion"
dict["en_US"][frame_options_name] = "Conversion Options"
dict["fr_FR"][frame_debug_name] = "Débogage"
dict["en_US"][frame_debug_name] = "Debugging"
dict["fr_FR"][frame_help_name] = "Aide"
dict["en_US"][frame_help_name] = "Help"
dict["fr_FR"][frame_threads_name] = "Nombre de threads"
dict["en_US"][frame_threads_name] = "Number of Threads"
dict['fr_FR'][frame_progress_name] = "Progression"
dict['en_US'][frame_progress_name] = "Progress"
dict['fr_FR'][frame_command_name] = "Commandes"
dict['en_US'][frame_command_name] = "Commands"

dict['fr_FR'][label_h264_name] = "Les fichiers H.264/H.265 sont marqués en rouge."
dict['en_US'][label_h264_name] = "H.264/H.265 files are marked in red."
dict['fr_FR'][label_help_files_name1] = "ATTENTION : toutes les vidéos sélectionnées seront traitées avec le mème format de conversion sélectionné dans l'onglet Options."
dict['en_US'][label_help_files_name1] = "PLEASE NOTE: All selected videos will be processed using the same conversion format selected in the Options tab."
dict['fr_FR'][label_help_files_name2] = "Choisir, donc, des vidéos qui ont le même format."
dict['en_US'][label_help_files_name2] = "Therefore, choose videos that have the same format."
dict['fr_FR'][label_forindv_name] = "Pour import Davinci Resolve"
dict['en_US'][label_forindv_name] = "For Davinci Resolve Import"
dict['fr_FR'][label_foroutdv_name] = "Après export Davinci Resolve"
dict['en_US'][label_foroutdv_name] = "For Davinci Resolve Export :"
dict['fr_FR'][label_otheropt_name] = "Autres options"
dict['en_US'][label_otheropt_name] = "Other options"
dict['fr_FR'][label_opt_recommanded] = "Les options recommandées sont en vert"
dict['en_US'][label_opt_recommanded] = "Recommended options are in green"
dict["fr_FR"][label_inwait] = "En attente"
dict["en_US"][label_inwait] = "Waiting.."

def get(key):
    return dict[lang][key] if key in dict[lang] else dict["en_US"][key]